name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  GITHUB_ORG_AND_REPO: "${{ github.repository }}"

jobs:
  push:

    strategy:
      matrix:
        image_name:
          - centos7
          - ubuntu1804

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push the image
        run: |
          github_org=${GITHUB_ORG_AND_REPO%%/*}
          if [[ $github_org == "yugabyte" ]]; then
            dockerhub_org="yugabytedb"
            dockerhub_user="yugabyteci"
          else
            dockerhub_org=$github_org
            dockerhub_user=$github_org
          fi
          github_repository="${{ github.repository }}
          bin/build_docker_images.sh \
            -i ${{ matrix.image_name }} \
            --tag_prefix "$dockerhub_org" \
            --tag_output_file docker_tag.txt

          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
            docker login -u "$dockerhub_org" --password-stdin

          docker_tag=$(<docker_tag.txt)
          echo "Docker tag: $docker_tag"
          docker push "$docker_tag"
